### ISSUE TITLE
Weather data / Barometric pressure

### ISSUE THREAD

**Issue by ScubyG** [MrReSc/Headi#15]
Can weather data be an option to add to a record such as atmosperic pressure

**Comment by MrReSc** [comment]
That's a good idea. I myself also notice the change in weather.
But automatically determining the air pressure seems to be a very difficult task because not all smartphones have a built-in sensor. Until now, I have deliberately avoided having an internet connection as a prerequisite. A manual input would be thinkable, but then you always have to look up the value and enter it.

What you can do is export your records as CSV and get the historical weather data for your location. Then you can use a spreadsheet to see if there is a correlation.

**Comment by tversteeg** [comment]
Maybe the OpenWeather API and the device location can be used to determine that automatically?

**Comment by MrReSc** [comment]
Yes that's right, I thought of that too. However, I find it unacceptable from a privacy point of view.

The app is intentionally designed to be as data-poor as possible. For this reason I have also created all the export possibilities to create further analyses if necessary.

PS: Thank you for your help, I was very happy about the translations.

**Comment by tversteeg** [comment]
Maybe if it was explicitly opt-in from the settings? The user has to enter their own API key anyway.

No problem :)

**Comment by MrReSc** [comment]
I think the idea is actually good and for some users it could also make sense.
But at the moment I would like to do without any network connections and I also don't find the query of the location necessary.

If there are more users with this wish, the topic can be discussed again.

I'm sorry @ScubyG, at the moment I'm not implementing this for privacy reasons.
