### ISSUE TITLE
Record pain strength while timer is running

### ISSUE THREAD

**Issue by tversteeg** [MrReSc/Headi#16]
It would be nice to be able to change the pain strength multiple times while a timer is running.

Currently, when I use the application I have a lot of small recordings with different levels, because the pain rarely is the same level over a long period of time.

I can imagine that this is quite a big feature request though..

**Comment by MrReSc** [comment]
Yes, I know the problem.
As you say, it would be a pretty big change.
You would still have to create a new record in the database for each change in pain strength (or even other parameters). Otherwise I would have to change the whole data structure - I don't want to do that.

Maybe you have an idea how to finish a recording and start a new one faster? This way, the data structure and the operating paradigm could be kept.

**Comment by tversteeg** [comment]
Maybe the small save button underneath the timer can still be active during recording and just ask for the strength and start a new one?

**Comment by MrReSc** [comment]
And what about the other parameters? Pain intensity is important for you at the moment. I know of another user for whom the pain region changes relatively quickly. I find it difficult to imagine a quick recording interface that covers all parameters. Especially the region. But I am open to concrete suggestions.

**Comment by tversteeg** [comment]
That's true, so it's probably best to keep the same option window, to not exclude other preferences.

**Comment by MrReSc** [comment]
So it is basically the same as if you press Stop, Save and then Start again :wink:.
I think the effort is too big to save the one click. If you are a programmer, you can try it, PR are welcome.
