### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by isteinbach** [MrReSc/Headi#23]
Since updating to 1.10.9, I have used Headi twice for logging periods of head aches. During both occasions, I saw heavy battery drain.

This does not happen normally and had not be observed while using 1.10.8 or previous.

Using F-Droid builds on FairPhone2 running /e/.

**Comment by MrReSc** [comment]
Unfortunately, I have no way to investigate the problem. I don't have a Fairphone and I don't have /e/. To be honest, I don't know how to investigate the problem either.

Since it doesn't happen every time, I don't think it's a Headi problem. If the problem occurs, are there other services / apps running?

If you give me a more detailed description, I can maybe give you some tips. Otherwise, I can't help you either.
