### ISSUE TITLE
Odd permissions

### ISSUE THREAD

**Issue by georgettica** [MrReSc/Headi#29]
Hey!
I wanted to use Headi but found it has the permissions of:
- prevent phone from sleeping
- run at startup
- run foreground service
- view network connections

Are all of these permissions required for the app to work?

I haven't read the code so this might just be a permission that is requested but never used.

Please fix / respond so I'll feel safer entering my personal information into the app

**Comment by MrReSc** [comment]
> - prevent phone from sleeping
> - run at startup
> - run foreground service 

Yes, these are needed so that the timer in the background and the notification display always work.

> - view network connections

I have not set the permission. You can see it in the [manifest](https://github.com/MrReSc/Headi/blob/master/app/src/main/AndroidManifest.xml). Either this is a bug or Android sets it itself. If you have installed the app, you will see in the permissions that no network is required.

**Comment by MrReSc** [comment]
@georgettica Now I can remember why network connection can be established. In the "About" screen there are links to the Github page and to the translation.

You can read the discussion in the F-Droid repo.
[https://gitlab.com/fdroid/rfp/-/issues/1680](https://gitlab.com/fdroid/rfp/-/issues/1680)

![grafik](https://user-images.githubusercontent.com/24952268/206977167-48166df7-41e1-41b5-8d82-85a00e5fcc21.png)

**Comment by georgettica** [comment]
The picture was more clear than the link.

Will install and use.
Thank you!
